### ISSUE TITLE
Проблема с кастомными ядрами

### ISSUE THREAD

**Issue by xteamlyer** [MisterZtr/recovery_device_realme_RMXTARO#3]
Привет! Не совсем в тему, но хотел бы спросить, вдруг найдется решение.
Есть [вот это GKI ядро](https://github.com/DarknessKiller/Overdose-5.10).
При его использовании, в рекавери (даже стоковое) не зайти.
Общался с разработчиком ([тг группа его проектов](https://t.me/MrDarknessK), [тг чат](https://t.me/thesphere_coffee/)) , у него нет идей как это пофиксить.
Хотел бы узнать, не найдется ли никаких идей для решения проблемы?

**Comment by MisterZtr** [comment]
Привет. Со стороны рекавери это не отдебагать, нужно со стороны ядра смотреть. Тот же Google gki boot работает в рекавери на этом смартфоне

**Comment by xteamlyer** [comment]
> Привет. Со стороны рекавери это не отдебагать, нужно со стороны ядра смотреть. Тот же Google gki boot работает в рекавери на этом смартфоне

Понял, спасибо за ответ. Тикет тогда пожалуй закрою.
